import 'package:country_code_picker/country_code_picker.dart';
import 'package:family_gathering/models/contact_way_model.dart';
import 'package:flutter/material.dart';

Iterable<Locale> supportedLocales = const [
  Locale("af"),
  Locale("am"),
  Locale("ar"),
  Locale("az"),
  Locale("be"),
  Locale("bg"),
  Locale("bn"),
  Locale("bs"),
  Locale("ca"),
  Locale("cs"),
  Locale("da"),
  Locale("de"),
  Locale("el"),
  Locale("en"),
  Locale("es"),
  Locale("et"),
  Locale("fa"),
  Locale("fi"),
  Locale("fr"),
  Locale("gl"),
  Locale("ha"),
  Locale("he"),
  Locale("hi"),
  Locale("hr"),
  Locale("hu"),
  Locale("hy"),
  Locale("id"),
  Locale("is"),
  Locale("it"),
  Locale("ja"),
  Locale("ka"),
  Locale("kk"),
  Locale("km"),
  Locale("ko"),
  Locale("ku"),
  Locale("ky"),
  Locale("lt"),
  Locale("lv"),
  Locale("mk"),
  Locale("ml"),
  Locale("mn"),
  Locale("ms"),
  Locale("nb"),
  Locale("nl"),
  Locale("nn"),
  Locale("no"),
  Locale("pl"),
  Locale("ps"),
  Locale("pt"),
  Locale("ro"),
  Locale("ru"),
  Locale("sd"),
  Locale("sk"),
  Locale("sl"),
  Locale("so"),
  Locale("sq"),
  Locale("sr"),
  Locale("sv"),
  Locale("ta"),
  Locale("tg"),
  Locale("th"),
  Locale("tk"),
  Locale("tr"),
  Locale("tt"),
  Locale("uk"),
  Locale("ug"),
  Locale("ur"),
  Locale("uz"),
  Locale("vi"),
  Locale("zh")
];

Iterable<LocalizationsDelegate<dynamic>>? localizationsDelegatesconst = [
  CountryLocalizations.delegate,
  // GlobalMaterialLocalizations.delegate,
  //GlobalWidgetsLocalizations.delegate,
];

Color? backgroundColor = const Color(0XFFee0097);

final String imgPath = "assets/images/";

final List<ConnectionWayModel> connectionWaysList = [
  ConnectionWayModel(contactImgPath: "$imgPath" "call.svg", onContactWayPressed: (){}),
  ConnectionWayModel(contactImgPath: "$imgPath" "sms.svg", onContactWayPressed: (){}),
  ConnectionWayModel(contactImgPath:  "$imgPath" "whatsapp.svg", onContactWayPressed: (){}),
  ConnectionWayModel(contactImgPath: "$imgPath" "telegram.svg", onContactWayPressed: (){}),
  ConnectionWayModel(contactImgPath: "$imgPath" "facebook.svg", onContactWayPressed: (){}),
  ConnectionWayModel(contactImgPath:  "$imgPath" "x.svg", onContactWayPressed: (){}),
  ConnectionWayModel(contactImgPath: "$imgPath" "messenger.svg", onContactWayPressed: (){}),
  ConnectionWayModel(contactImgPath: "$imgPath" "instagram.svg", onContactWayPressed: (){}),
  ConnectionWayModel(contactImgPath: "$imgPath" "gmail.svg", onContactWayPressed: (){}),

  ConnectionWayModel(contactImgPath: "$imgPath" "yahoo.svg", onContactWayPressed: (){}),
  ConnectionWayModel(contactImgPath: "$imgPath" "youtube.svg", onContactWayPressed: (){}),
  ConnectionWayModel(contactImgPath: "$imgPath" "tiktok.svg", onContactWayPressed: (){}),
  ConnectionWayModel(contactImgPath: "$imgPath" "linkedin.svg", onContactWayPressed: (){}),
  ConnectionWayModel(contactImgPath: "$imgPath" "instapay.svg", onContactWayPressed: (){}),
  ConnectionWayModel(contactImgPath: "$imgPath" "paypal.svg", onContactWayPressed: (){}),
];
