// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTTisCL66BwAaIwGTo1lFoxh-r7S8JYso',
    appId: '1:920005911914:web:fd243f705f8c77ab877113',
    messagingSenderId: '920005911914',
    projectId: 'familly-gathering',
    authDomain: 'familly-gathering.firebaseapp.com',
    storageBucket: 'familly-gathering.firebasestorage.app',
    measurementId: 'G-9C30G9V41G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7KihxkQSmI8jaRpPBXA7eBsLNKz-OB-w',
    appId: '1:920005911914:android:995c8f9e0bddb484877113',
    messagingSenderId: '920005911914',
    projectId: 'familly-gathering',
    storageBucket: 'familly-gathering.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8rNeGEeyQxuXDaVpEl8Kq4aTLh-rrl_A',
    appId: '1:920005911914:ios:c76b81e20ee97087877113',
    messagingSenderId: '920005911914',
    projectId: 'familly-gathering',
    storageBucket: 'familly-gathering.firebasestorage.app',
    iosBundleId: 'com.example.familyGatheringV0',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8rNeGEeyQxuXDaVpEl8Kq4aTLh-rrl_A',
    appId: '1:920005911914:ios:c76b81e20ee97087877113',
    messagingSenderId: '920005911914',
    projectId: 'familly-gathering',
    storageBucket: 'familly-gathering.firebasestorage.app',
    iosBundleId: 'com.example.familyGatheringV0',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTTisCL66BwAaIwGTo1lFoxh-r7S8JYso',
    appId: '1:920005911914:web:65cf915afc8c3e50877113',
    messagingSenderId: '920005911914',
    projectId: 'familly-gathering',
    authDomain: 'familly-gathering.firebaseapp.com',
    storageBucket: 'familly-gathering.firebasestorage.app',
    measurementId: 'G-BN8KVZGHG9',
  );

}